version: "3.9"
   
services:
  db:
    image: postgres
    # ports:
    #   - "5432:5432"
    environment:
    
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "sudo mkdir /var/log/gunicorn && sudo supervisorctl reread && sudo supervisorctl update && sudo ln django.conf /etc/nginx/sites-enabled/ && sudo nginx  "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      # - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db