# Generated by Django 4.0.4 on 2022-05-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_remove_tag_space_space_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='tags',
        ),
        migrations.AddField(
            model_name='space',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
