# Generated by Django 4.0.4 on 2022-05-21 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0005_space_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='user',
        ),
        migrations.AddField(
            model_name='space',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
